In [132]:
import numpy as np
from numpy import linalg

In [154]:
def _get_sorted_nparray():
    n = int(input('Введите значение N: '))
    return np.arange(0,n)[::-1]

In [158]:
def _create_matrix():
    a = _get_sorted_nparray()
    print('-'*10)
    print('Диагональная матрица:\n')
    print(np.diag(a))
    print('-'*10)
    print('Сумма значений на диагонали:')
    print(sum(a))

## Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [156]:
_get_sorted_nparray()

Введите значение N: 10


array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

## Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [159]:
_create_matrix()

Введите значение N: 10
----------
Диагональная матрица:

[[9 0 0 0 0 0 0 0 0 0]
 [0 8 0 0 0 0 0 0 0 0]
 [0 0 7 0 0 0 0 0 0 0]
 [0 0 0 6 0 0 0 0 0 0]
 [0 0 0 0 5 0 0 0 0 0]
 [0 0 0 0 0 4 0 0 0 0]
 [0 0 0 0 0 0 3 0 0 0]
 [0 0 0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0]]
----------
Сумма значений на диагонали:
45


## Задание 3
Решите систему уравнений:
##### 4x + 2y + z = 4
##### x + 3y = 12
##### 5y + 4z = -3

In [134]:
# коэффициенты при переменных в левой части уравнения
a = np.array( [ [4, 2, 1], [1, 3, 0], [0, 5, 4]] )
# значения в правой части уравнения
b = np.array( [4, 12, -3] )
linalg.solve(a,b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [135]:
# проверка верности
np.allclose( np.dot(a, linalg.solve(a, b)), b )

True